export const SDK_STATES = {
    NOT_INITIALIZED : 'NOT_INITIALIZED',
    INITIALIZED: 'INITIALIZED'
};

export const ACTIVITY_STATES = {
    USER_ACTIVITY_TYPE_STATIONARY : 'USER_ACTIVITY_TYPE_STATIONARY',
    USER_ACTIVITY_TYPE_TRIP : 'USER_ACTIVITY_TYPE_TRIP',
    USER_ACTIVITY_TYPE_UNKNOWN : 'USER_ACTIVITY_TYPE_UNKNOWN'
}

export const TRIP_TYPES = {
    TRIP : 'TRIP',
    STATIONARY: 'STATIONARY',
    UNKNOWN: 'UNKNOWN'
}
